export function renderOnboarding(root, { user, initialPreferences, onComplete }) {
  let step = 1;
  const values = { homeCity: initialPreferences?.homeCity || "Bengaluru", unit: initialPreferences?.unit || "metric", theme: initialPreferences?.theme || "system" };
  const render = () => {
    root.innerHTML = `<main class="onboarding-shell"><nav class="nav"><a class="brand" href="#">chameleon<span>.</span></a><span class="step-count">STEP ${step} OF 2</span></nav><section class="onboarding-card"><div class="progress"><i style="width:${step * 50}%"></i></div>${step === 1 ? `<p class="eyebrow">HELLO, ${user.fullName.toUpperCase()}</p><h1>Where do you call home?</h1><p>We’ll use this to prepare your daily weather briefing.</p><label class="large-label">Home city<input id="city" value="${values.homeCity}" placeholder="e.g. Bengaluru" autofocus /></label><p class="helper">You can always search for another city later.</p><button class="button button-primary" id="next">Continue <span>→</span></button>` : `<p class="eyebrow">MAKE IT COMFORTABLE</p><h1>Set your weather style.</h1><p>Choose how you want your dashboard to feel.</p><fieldset><legend>Temperature</legend><label class="choice"><input type="radio" name="unit" value="metric" ${values.unit === "metric" ? "checked" : ""} /> Celsius <small>°C</small></label><label class="choice"><input type="radio" name="unit" value="imperial" ${values.unit === "imperial" ? "checked" : ""} /> Fahrenheit <small>°F</small></label></fieldset><fieldset><legend>Appearance</legend><label class="choice"><input type="radio" name="theme" value="system" ${values.theme === "system" ? "checked" : ""} /> System default</label><label class="choice"><input type="radio" name="theme" value="dark" ${values.theme === "dark" ? "checked" : ""} /> Night mode</label></fieldset><div class="wizard-actions"><button class="button button-quiet" id="back">Back</button><button class="button button-primary" id="finish">Open dashboard <span>→</span></button></div>`}</section></main>`;
    if (step === 1) root.querySelector("#next").addEventListener("click", () => { const city = root.querySelector("#city").value.trim(); if (!city) return; values.homeCity = city; step = 2; render(); });
    else { root.querySelector("#back").addEventListener("click", () => { step = 1; render(); }); root.querySelector("#finish").addEventListener("click", () => { values.unit = root.querySelector('input[name="unit"]:checked').value; values.theme = root.querySelector('input[name="theme"]:checked').value; onComplete(values); }); }
  };
  render();
}
